classification: mechanical
color: ''
description_extra: ''
description_main: cricut_maker_compatible
id: mechanical_motor_with_encoder_30_mm_diameter_cricut_maker_compatible
manufacturer: ''
part_number: ''
size: 30_mm_diameter
type: motor_with_encoder
