classification: mechanical
color: ''
description_extra: ''
description_main: 42_mm_width_42_mm_height_48_mm_depth
id: mechanical_motor_stepper_nema_17_42_mm_width_42_mm_height_48_mm_depth
manufacturer: ''
part_number: ''
size: nema_17
type: motor_stepper
